---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
  - directory: github
    package-ecosystem: github-actions
    schedule:
      interval: monthly